"""setup user and book relations, add review table and relations

Revision ID: 2cae46661fc9
Revises: 23df00ff6054
Create Date: 2026-03-10 14:56:04.913232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cae46661fc9'
down_revision: Union[str, Sequence[str], None] = '23df00ff6054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_uid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_uid')
    # ### end Alembic commands ###
