"""Modification de l'attribut du champs published_date de str en DateTime

Revision ID: 8eab47530880
Revises: 17784817d38b
Create Date: 2026-03-03 17:26:42.775771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eab47530880'
down_revision: Union[str, Sequence[str], None] = '17784817d38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'published_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='published_date::timestamp with time zone', # <-- AJOUTE CECI
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'published_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
